apiVersion: v2
name: rnc-platform
description: RNC — Réseau National de Confiance — Helm Chart pour déploiement Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://rnc.bf
sources:
  - https://gitlab.rnc.bf/rnc/platform
maintainers:
  - name: Équipe Architecture RNC
    email: devops@rnc.bf
keywords:
  - microfinance
  - nano-credit
  - burkina-faso
  - trust
  - financial-inclusion
